//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newtype.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("newtype.Database.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SELECT
        ///    b.name as &quot;tableName&quot;,
        ///    a.name as &quot;columnName&quot;,
        ///    c.name as &quot;type&quot;,
        ///    a.column_id as &quot;order&quot;,
        ///    a.max_length as &quot;length&quot;,
        ///    a.precision,
        ///    a.scale,
        ///    case
        ///        when a.is_nullable = 0
        ///        then &apos;×&apos;
        ///        else &apos;〇&apos;
        ///    end as &quot;boolnull&quot;,
        ///    case
        ///        when a.is_identity = 0
        ///        then &apos;0&apos;
        ///        else &apos;1&apos;
        ///    end as &quot;オートナンバー&quot;,
        ///    case
        ///        when a.default_object_id = 0
        ///        then &apos;×&apos;
        ///        else d.definition
        ///    end as &apos;デフォルト値&apos;,
        ///    case
        ///     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMNS {
            get {
                return ResourceManager.GetString("COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT name FROM sys.databases ORDER BY database_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に失敗しました。接続設定を開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE01 {
            get {
                return ResourceManager.GetString("MESSAGE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE02 {
            get {
                return ResourceManager.GetString("MESSAGE02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select 
        ///table_name as &apos;tableName&apos;,
        ///column_name as &apos;columnName&apos;,
        ///data_type as &apos;type&apos;,
        ///character_maximum_length as &apos;length&apos;,
        ///case 
        ///when is_nullable = &apos;NO&apos;
        ///then &apos;×&apos;
        ///else &apos;〇&apos;
        ///end as &apos;boolnull&apos;,
        ///column_key as &apos;pk&apos;
        ///from information_schema.columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MYCOLUMNS {
            get {
                return ResourceManager.GetString("MYCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOW Databases; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MYDATABASE {
            get {
                return ResourceManager.GetString("MYDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select 
        ///T.table_name as &apos;Name&apos;,
        ///cast(T.table_rows as signed int) as &apos;Rows&apos;,
        ///cast(count(*) as signed int) as &apos;Columns&apos;
        ///from 
        ///information_schema.Tables T
        ///left outer join information_schema.columns C
        ///on
        ///T.table_catalog = C.table_catalog
        ///and
        ///T.table_schema = C.table_schema
        ///and
        ///T.table_name = C.table_name
        ///where T.table_schema=&apos;{0}&apos;
        ///group by 
        ///T.table_catalog,
        ///T.table_schema,
        ///T.table_name,
        ///T.table_rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MYTABLES {
            get {
                return ResourceManager.GetString("MYTABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT 
        ///c.table_name as tableName,
        ///c.column_name as columnName,
        ///c.data_type as type,
        ///c.character_maximum_length as length,
        ///case 
        ///when is_nullable = &apos;NO&apos;
        ///then &apos;×&apos;
        ///else &apos;〇&apos;
        ///end as boolnull,
        ///case 
        ///when tc.constraint_type = &apos;PRIMARY KEY&apos;
        ///then &apos;〇&apos;
        ///else &apos;×&apos;
        ///end as pk
        ///      FROM information_schema.columns c
        ///LEFT OUTER JOIN information_schema.constraint_column_usage ccu
        ///        ON c.table_name       = ccu.table_name
        ///       AND c.column_name      = ccu.column_name 
        ///LEFT OUTER JOIN information_schema.table_constrai [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PGCOLUMNS {
            get {
                return ResourceManager.GetString("PGCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT datname as name FROM pg_database; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PGDATABASE {
            get {
                return ResourceManager.GetString("PGDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select 
        ///	relname as Name 
        ///from 
        ///	pg_stat_user_tables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PGTABLES {
            get {
                return ResourceManager.GetString("PGTABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select o.name as Name, i.Rows as &apos;Rows&apos;, count(s.column_id) as Columns from sysindexes i, sysobjects o inner join sys.columns s on s.object_id = o.id where o.xtype = &apos;U&apos; and o.id = i.id and i.indid &lt; 2 and o.name &lt;&gt; &apos;dtproperties&apos; group by o.name, i.Rows order by o.name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TABLES {
            get {
                return ResourceManager.GetString("TABLES", resourceCulture);
            }
        }
    }
}
